name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ghizlanera }}
        password: ${{ secrets. }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghizlanera/odoo-custom:latest
